version: "3.9"

services:
  backend:
    build: ./backend
    container_name: uqcourse-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/courses.db:/app/courses.db
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  backend-tests:
    build: ./backend
    depends_on:
      - backend
    command: sh -c "PYTHONPATH=. pytest tests/"
    volumes:
      - ./backend:/app
