version: "3.9"

services:
  backend:
    build: ./backend
    container_name: uqcourse-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/courses.db:/app/courses.db
    command: uvicorn main:app --host 0.0.0.0 --port 8000
