name: Backend Tests

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/test.yml'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: python:3.11
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and run tests
        run: docker compose run backend-tests
