name: Backend Tests

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/test.yml'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run backend container
        run: docker compose up -d backend

      - name: Wait for backend start
        run: |
            echo "Waiting for backend..."
            for i in {1..10}; do
                curl -s http://localhost:8000/docs && exit 0
                sleep 3
            done
            echo "Backend did not start in time" >&2
            exit 1

      - name: Run backend tests
        run: docker compose run --rm backend-tests
