name: Backend Tests

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/test.yml'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:24.0.6
        options: --privileged
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: docker-compose up -d backend

      - name: Run backend tests
        run: docker-compose run --rm backend-tests
